
// Quote storage. Each quote needs the text, surrounded by single or double quotes and the author
// surrounded by the same.
// To add more quotes, just follow this schematic: 
// Add these (let's call them quote objects)
//
// {
//   text: 'Genius is one percent inspiration and ninety-nine percent perspiration.',
// },
// into the array which means place the above within the []. so it would follow this pattern
// const localQuotes = [quoteObject1, quoteObject2, quoteObject3] 
const localQuotes = [
  {
    text: 'Tiny relationship win! I (26F) finally pushed back on my mothers (49F) terrible gift-giving and asked for what I want!',
  },
  {
    text: 'How do I tell my mom that her ‘best friend‘ is going after my dad?',
  }, 
  {
    text: 'My wife (F29) was sexuality assaulted and is pregnant. I feel like a monster for wanting to leave. (M30)',
  },
  {
  	text: 'My (29M) wife (30F) of over a decade has been having an affair since early fall. Now I am at a loss on what to do next.',
  },
  {
  text: 'My(15F) step-father(49M) and mother(43F) want me to cut all contact with the step-sister(18F) I just met, because of something they arent telling me. Should I ask her what is going on or wait for them to explain?',
  },
  {text: 'My(17F) dad slept with a close friend(18F) and classmate of mine and it’s the talk of the school and now everyone knows and it’s fucking up my life',},
  {text: 'Don’t know how to tell my sister (23f) her ex (25f) and I (27M) are gonna have a baby',},
  {text: 'My bf has a Minecraft gf on a server I play on too, and I feel like it’s stupid to feel upset.',},
  {text: 'I left my boyfriend yesterday after he showed he didnt care about my health and am now in a womens shelter. I think I did the right thing but dont have many people to talk to about it.',},
  {text: ' my boss is getting divorced, I’m worried I’m a target for rebound.',},
  {text: 'My (25M) wife (25F) is wanting a divorce because she thinks she isnt good for me',},
  {text: 'My(29M) marriage feels like a prison and my wife(28F) is my warden',},
  {text: 'How do I (F23) ask or get my boyfriend (M28) to cuddle with me naked? Looking for advice',},
  {text: 'My boyfriend is saying that I don’t care about his physical health and I’m having a hard time trying to understand where I did wrong',},
  {text: 'My (Almost 30 M) best MALE & STRAIGHT friend (Same-ish age) just confessed last night that hes been "Thinking about kissing me". HELP',},
  {text: 'My (20F) boyfriend (20M) is really insecure and it turns me off like a switch.',},
  {text: 'Talking to GF about friend-couple where wife is primary earner. When told, my GF replied with "well why is she with him then?" I am primary breadwinner and hear a flag waving, what about yall?',},
  {text: 'Girlfriend (28F) wants me (28M) to propose by March or she’s leaving.',},
  {text: '(28M) Single parent. I am trying my best with what I have left.',},
  {text: 'Having a hard time with my alcoholic baby mama.',},
  {text: 'Need Advice- My F23 Boyfriend M27 pulls my hair while we are intimate and it hurts so much',},
  {text: 'People in long term relationships/marriages, with kids or without, how do you keep that passion alive? What to do to avoid "roomates not lovers" situation.? Is it possible in real life or that just exists in movies?',},
  {text: 'I(24F) rejected a guy(25M) because he asked to come alone to his house for the night and even when I said no, he was quite adamant about it.',},
  {text: 'I think? I am being mentally abused?',},
  {text: 'Gifted a hammy-down from an ex....',},
  {text: 'my mom told me i lied about being raped',},
  {text: 'Should I (29M) be worried that my GF (27F) is using my preferences around personal privacy as an indicator for shared values in our relationship?',},
  {text: 'My girlfriend (25f) really wants to go to a SeaWorld equivalent and I (23m) dont know how to tell her I dont want to support them for the way they treat animals',},
  {text: 'Boyfriend/ex won’t give my stuff back and instead ignores me?',},
  {text: 'Am I (23M) overreacting when my (23F) girlfriend says “goodnight ❤️” to people she’s shown interest in?',},
  {text: 'I caught my mom cheating with a family friend.',},
  {text: '17f step daughter is causing issues in my home for me 47m and my wife 51f.',},
  {text: 'Very inappropriate things in his phone',},
  {text: 'Possibly depressed Husband (30M) seeks an even higher paying career in an attempt to seek happiness. I (30F) fear that he is turning into a self-centered finance-bro and worry about what he is willing to sacrifice for the chance of happiness',},
  {text: 'My sister is having an affair with one of her patients and I do not know wether I should report her or let her fiance know.',},
  {text: 'My mom won’t stop yelling at me to the point it effects my relationship with others.',},
  {text: 'My(25F) bfs (25M) jokes are not funny and it is mentally hurting me',},
  {text: 'UPDATE: Should I (25m) stop inviting my friends (22m) ex (23f) to our gaming nights after their messy breakup?',},
  {text: 'My (28F) husband (30M) raped me and I’m not sure how to process it healthily',},
  {text: '23F finally left boyfriend',},
  {text: 'my (16f) mom (47f) was talking to her ex (30ish m) that she cheated on my dad (47m) with and her ex got involved in a conversation that he wasnt involved in',},
  {text: 'A (40 M ) guy think we (me 23 F ) date and calls me his girlfriend. I try to make him understand that we arent but he cant get it. What should I do?',},
  {text: 'I broke up with my girlfriend, and now I dont know what to do',},
  {text: 'I want to adopt 1 of my volunteer doggo\'s, but I\'m not sure how to approach it with his owner.',},
  {text: 'How can I get my wife to honor my wishes if I develop dementia?',},
  {text: 'Marriage counseling for poor people?',},
  {text: 'I am in a relationship with someone I dont have feelings for, I am not one bit interested in them in any way. (15F) I said yes to him (16M) because I didnt want to hurt his feelings.',},
  {text: 'I have [27M] been quarantining for Christmas to see my family, found out little sister [20F] is taking a weeklong vacation to Disney Land the week before Christmas.',},
  {text: 'How weird is it for one spouse to have their own “getaway home” in another country?',},
  {text: 'My brother is being used and I feel helpless. How do I get him to wake up?',},
  {text: 'My boyfriend (22M) wants to track my texts (21F)',},
  {text: 'I [43F] left my husband [55M] after 19 years of a sexless marriage and moving him out of state. Is that wrong?',},
  {text: 'Lost after being broken up with',},
  {text: 'My (29f) BF (26m) is too intense and I think slightly manipulative. He just (I think) almost proposed this weekend after only 5 weeks of dating. My mental health issues are going crazy and I’m not sure if it’s him or the pandemic! Help!',},
  {text: 'Long, relationship advice/venting.',},
  {text: 'He works with his ex.',},
  {text: 'My (M19) girlfriend (F19) complains about the stimulation of sex being too much for her to handle.',},
  {text: 'I (21M) have developed feelings for my (21F) friend but dont know how to tell her',},
  {text: 'Kiss their Insecurites',},
  {text: 'I (29M) was awarded custody of my daughters after they were abused by their grandmother (50F), but things are far from done',},
  {text: 'My boyfriend is lazy',},
  {text: 'My boyfriend (29) does not like to apologize and complains (I am 20)',},
  {text: 'Sex drive decreased noticeably after moving in together... why could it be?',},
  {text: 'My gf (18f) wants the d but I am (19 nb) not ready. shes respectful but frustrated and i still want to satisfy her',},
  {text: 'Advice on how to move forward with this guy?',},
  {text: 'Is she leading me on',},
  {text: 'My sister is cheating on her husband and it makes me feel really terrible.',},
  {text: 'I do not think there is any helping, but I needed to write it',},
  {text: 'I(24f) saw a screenshot of my boyfriend’s(27m) tinder profile. Any chance it’s an old one?',},
  {text: 'Gay girl missing sex w men',},
  {text: 'My (F24) boyfriend (M28) told me his ex text him because he wanted to be honest with me ... My friends are saying he is cheating and covering his tracks?',},
  {text: 'My bf (24) and I (24) have recently started to date and he tends to bring up his ex often.',},
  {text: 'My boyfriend has lied and cheated on me quite a few times so why don’t I hate him?',},
  {text: 'My boyfriend (21m) has never taken me (23f) on a date. I have talked to him about it and no action has been taken. Why?',},
  {text: 'What do women find most attractive in a man?',},
  {text: 'My dad is cheating on my mom with a coworker and I don’t know what to do',},
  {text: 'Almost married? :/',},
  {text: 'Discovered... an affair?',},
  {text: 'My [26f] boyfriend [29M] confessed to raping someone when they were both under the influence of MDMA. She said no, but "he really needed that nut."',},
  {text: 'When I was 14, my then boyfriend abused me. Now, I don’t enjoy sex anymore.',},
  {text: 'My best friends son is beating her',},
  {text: 'My parents bought my boyfriend the ugliest Christmas present',},
  {text: 'Recently discovered that my (26F) friends purposely exclude me and hang out together',},
  {text: 'My Girlfriend opened up and I am stressing about it',},
  {text: 'My girlfriend is debating being gay',},
  {text: 'My [25F] boyfriend [24M] took out a new car on finance that he cannot afford.',},
  {text: 'NEED ADVICE SOS',},
  {text: 'Bf mother is still insisting to visit after someone in her house has covid',},
  {text: 'Fear of being cheated on',},
  {text: 'My boyfriend and I are having a clash over what privacy is regarding texting',},
  {text: 'Girlfriend',},
  {text: 'My[20m] ex [17f] wants me to help on her test',},
  {text: 'Why does she always have some woke excuse for slowly ruining my life?',},
  {text: 'Future MIL [F/49] wants nothing to do with us [F/25 and M/28] after we brought up valid questions about her plan to move in with us temporarily',},
  {text: 'My girlfriend said she feels like something is missing from our relationship but she doesn’t know what.',},
  {text: 'Should I maintain a relationship with a child I (28M) had through a condom with an ex (23F) who cheated on me?',},
  {text: 'toxic shit parents say',},
  {text: 'Is it rude of me to stop talking to my grandma?',},
  {text: 'Girlfriend has DID. It’s complicated..',},
  {text: 'My GF is driving me nuts... I just need some advice... Me (37M), GF (34F).',},
  {text: 'My parents just gave me a graduation gift and it means almost nothing to me and I feel terrible.',},
  {text: 'What is the best way to decline a Relationship without breaking the other persons feelings?',},
  {text: 'My girlfriend of three years is polyamorous, non-binary, and asexual. Right now we’re in a monogamous relationship. She started talking to the only ex she has that they ended things on a good note. I was fine with it since they’re just friends and he lives far away. PLEASE HELP ME.',},
  {text: 'Emotionally Unavailable Girlfriend or Needy Boyfriend?',},
  {text: 'Guy I have no plans to pursue a relationship with won’t back down.',},
  {text: 'Confused on waiting (24F) (23m)',},
  {text: 'I (24M) am the biggest douche in history for not accepting a girls past.',},
  {text: 'What can I do about my [31F] toxic friend [33F]?',},
  {text: 'My boyfriend says no to doing fun activities with me, but then goes and does them with others',},
  {text: 'I love my friend but not sure if she does too',},
  {text: 'My girlfriend is faking orgasms. How do I address it with her?',},
  {text: 'Old friend acts like we are still besties?',},
  {text: 'Why are some guys on dating apps with no intent to date and only make conversation?',},
  {text: 'Boyfriend has a female friend that gets to me',},
  {text: 'How do i ask her out?',},
  {text: 'Need some advice',},
  {text: 'Help please',},
  {text: 'I (f23) think that my roomate/best friend (f25) has autism and I dont know what to do.',},
  {text: 'My abusive gf',},
  {text: 'Will I lose my step-son if my wife and I split up?',},
  {text: 'Did I do anything wrong, because we weren’t in a relationship? Please help :(',},
  {text: 'Is she playing with my feelings',},
  {text: 'How do I avoid telling my SO about a grade I am not happy with?',},
  {text: 'I (22F) met with my ex (23F) in January, and it was. Weird. Now I want to see her again. How should I proceed?',},
  {text: 'My(20f) mom(45f) might be cheating on my dad (49m). How do I deal with the situation???',},
  {text: 'My (23F) boyfriend (24M) offered to insert a cucumber into his butt to make up for cheating on me',},
  {text: 'I (25F) dont know what to do about my boyfriends (25m) increased usage of Marijuana',},
  {text: 'He lied about having a tinder, what should I do?',},
  {text: 'How to deal with bigoted family members over the holidays?',},
  {text: 'Boyfriends (m24) sister (f15) keeps coming to hug and cuddle him while we are on video call',},
  {text: 'Response to ghosting',},
  {text: 'my (19f) girlfriend (21f) runs back to her toxic friends and i don’t know what to do',},
  {text: 'Need Honest Convo Feedback...Did I 32(F) communicate well? to 36(M) , ~2 month long "situationship"',},
  {text: 'Not over my ex',},
  {text: 'My gfs mom is trying to break us up, I don’t know what to do. I think she’s gonna stop us from seeing each other. She wants her to switch schools. What the fuck do I do',},
  {text: 'Is my girlfriend using reverse psychology on me?',},
  {text: 'I (20F) saw my boyfriend (21M) fighting, now Im scared of him',},
  {text: 'Trying to figure out how I (33m) should feel about what my gf (35f) did while I was gone',},
  {text: 'I want to surprise my boyfriend for Valentine’s Day.',},
  {text: 'Psychological ED?',},
  {text: 'Positive intimacy and sexuality',},
  {text: 'Should I (28M) be accepting money from my brother that was not his to begin with?',},
  {text: 'Should I talk to the girl I have liked for a while?',},
  {text: 'My boyfriend [26] wants to break up with me [18] cause his best friend had a crush on me.',},
  {text: 'My boyfriend (18M) and I (20F) have an amazing relationship until my past gets brought up. Need advice for both sides! TIA!',},
  {text: 'How do I get my partner to understand that his actions upset me, whether they are down to his mental health or not?',},
  {text: 'Will social media ever be more important than a relationship?',},
  {text: 'what should i do?',},
  {text: 'Drunken psychosis',},
  {text: 'I (23M) am texting with a girl for a while but I don’t know if she’s interested and what to do',},
  {text: 'Am I bad person for dumping my girlfriend',},
  {text: 'I (F ) really like a guy ... dont sure if I should tell him about it',},
  {text: 'how is it possible for a girl to act so into you but then say that she isnt into you ?',},
  {text: 'My (24F) boyfriend (26M) accused me of flirting with/being attracted to another guy at a friend’s Christmas party',},
  {text: 'I feel distant from my boyfriend but I dont know if its temporary',} 
  
];
